name: update

on:
  push:
    branches: # Requires that main is restricted (and why wouldn't it be?)
      - main

jobs:
  compute-number:
    runs-on: ubuntu-latest

    concurrency: # Ensures that only a single action runs at a time
      group: numbering
      cancel-in-progress: false

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # install the python version needed

      # TODO write this in bash as to remove the Python dependency
      - name: run python script to get the latest number
        id: py-script
        run: echo "NEXT_VALUE=$(python main.py)" >> "$GITHUB_OUTPUT"

      - name: show-me-the-value
        env:
          COUNTER: ${{ steps.py-script.outputs.NEXT_VALUE }}
        run: echo "Next USN value is ${COUNTER}?"

      - name: check if candidate file exists
        id: check-candidate
        run: |
          if [[ ! -f ./candidate/candidate-usn ]];
          then
            echo "SKIP=true" >> "$GITHUB_OUTPUT"
          fi

      - name: rename the file
        env:
          COUNTER: ${{ steps.py-script.outputs.NEXT_VALUE }}
        if: ${{ ! steps.check-candidate.outputs.SKIP }}
        run: |
          sed -i "s/{{USN}}/$COUNTER/g" ./candidate/candidate-usn
          mv ./candidate/candidate-usn ./sn/SN-${COUNTER}

      - name: Commit files
        if: ${{ ! steps.check-candidate.outputs.SKIP }}
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add --all
            git commit -m "Updating numbers DB"

      - name: Push changes
        if: ${{ ! steps.check-candidate.outputs.SKIP }}
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
