name: update

on:
  push:
    branches: # Requires that main is restricted (and why wouldn't it be?)
      - main

jobs:
  compute-number:
    runs-on: ubuntu-latest
    concurrency: # Ensures that only a single action runs at a time
      group: numbering
      cancel-in-progress: false
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # install the python version needed

      - name: run python script to get the number
        id: py-script
        run: echo "NEXT_VALUE=$(python main.py)" >> "$GITHUB_OUTPUT"

      - name: show-me-the-value
        env:
          COUNTER: ${{ steps.py-script.outputs.NEXT_VALUE }}
        run: echo "Can you believe that the next value is ${COUNTER}?"

      - name: rename the file
        env:
          COUNTER: ${{ steps.py-script.outputs.NEXT_VALUE }}
        run: cp ./candidate/* ./sn/SN-${COUNTER}

      - name: Commit files
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add --all
            git commit -m "Updating numbers DB"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
