name: update

on:
  push:
    branches: # Requires that main is restricted (and why wouldn't it be?)
      - main

jobs:
  compute-number:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # install the python version needed

      - name: py-script
        run: |
          CAPTURE=$(python main.py)
          echo "Testing: NEXT_VALUE=${CAPTURE}"
          echo "NEXT_VALUE=${CAPTURE}" >> "$GITHUB_OUTPUT"

      - name: show-me-the-value
        env:
          COUNTER: ${{ steps.py-script.outputs.NEXT_VALUE }}
        run: echo "Can you believe that the next value is ${COUNTER}?"
